// <auto-generated />
namespace RESTService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedgoogleidtouserobject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedgoogleidtouserobject));
        
        string IMigrationMetadata.Id
        {
            get { return "201701252025480_added google id to user object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
